### ISSUE TITLE
required packages not installed by pip

### ISSUE THREAD

**Issue by BenMiller002** [stemtool/stemtool#1]
Today I tried installing stemtool using pip, and this appeared to work well. However, when I tried to use stemtool, I got several ModuleNotFoundErrors because several packages which stemtool tries to import were not installed during the pip install. The 2 I've tracked down so far are  matplotlib-scalebar and ase, but there may be others.

**Comment by debangshu-mukherjee** [comment]
Thanks @BenMiller002 for noticing. I pushed a new release to PyPi - `0.532` which has now an updated `setup.py` file. If it installs without problems I will close the issue
